Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -389,9 +389,11 @@ runs:
         #echo "" > ${{ env.EXTERNAL_DIR }}/UNIT_TEST_RESULTS.txt
         ls
         pwd
+        docker ps -a | grep $CONTAINER_ID
         #bash ${{ env.EXTERNAL_DIR }}/run_docker.sh "cd /myworkspace && ${{ inputs.unit_test_command }} 2>&1 | tee /myworkspace/UNIT_TEST_RESULTS.txt" || true
         #bash ${{ env.EXTERNAL_DIR }}/run_docker.sh -c "ls && cd /myworkspace && pytest -v 2>&1 | tee UNIT_TEST_RESULTS.txt"
         docker exec -i $CONTAINER_ID bash -c "cd /myworkspace && pwd" 
+        docker exec -i $CONTAINER_ID bash -c "cd /myworkspace && pwd" || { echo "Command failed"; exit 1; }
         echo "Unit Test Results: $(cat UNIT_TEST_RESULTS.txt)"
         echo "UNIT_TEST_RESULTS=$(cat UNIT_TEST_RESULTS.txt)" >> $GITHUB_ENV
       shell: bash
